name: friendzone
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  # attempt to download flutterflow 안됨 ㅋ
  # flutterflow_ui: ^0.2.0
  #
  flutter:
    sdk: flutter
  #hell yeah we adding googlmaps boyyyy 20240727|23:17
  location: ^7.0.0
  google_maps_flutter: ^2.5.3


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/background_blue.png


  fonts:
    - family: BigShouldersDisplay
      fonts:
        - asset: fonts/BigShouldersDisplay-Regular.ttf
    - family: BigShouldersText
      fonts:
        - asset: fonts/BigShouldersText-Regular.ttf
        - asset: fonts/BigShouldersText-Bold.ttf
        - asset: fonts/BigShouldersText-SemiBold.ttf
          weight: 700
    - family: TurretRoad
      fonts:
        - asset: fonts/TurretRoad-Regular.ttf
      
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
