// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMM8ayi4HyyvZVCPS1NjRSmy3ERG0ChLQ',
    appId: '1:865928637202:web:519c4d33bbbd15e2e961cb',
    messagingSenderId: '865928637202',
    projectId: 'friendzone-dpju0q',
    authDomain: 'friendzone-dpju0q.firebaseapp.com',
    storageBucket: 'friendzone-dpju0q.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBuqGpIwGcLyMKXPi4wpaZb9LnYFSY43Q',
    appId: '1:865928637202:android:7216f54de7da5b6fe961cb',
    messagingSenderId: '865928637202',
    projectId: 'friendzone-dpju0q',
    storageBucket: 'friendzone-dpju0q.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1Zn6CkfL2U2uAqZ5Jc2DqqTNrdVF66A',
    appId: '1:865928637202:ios:7ecbd7c00cc3a63de961cb',
    messagingSenderId: '865928637202',
    projectId: 'friendzone-dpju0q',
    storageBucket: 'friendzone-dpju0q.appspot.com',
    iosBundleId: 'com.example.friendzone',
  );
}
